### ISSUE TITLE
Allocation bug?

### ISSUE THREAD

**Issue by pdematteis** [zorxx/saxml#1]
In saxml.c, line 83, allocation is made as:
`ctxt = (tParserContext *) malloc(sizeof(*context));`
but `ctxt` is of type `tParserContext`, while `context` is of type `tSaxmlContext`.
So... why `sizeof(*context)`?

**Comment by zorxx** [comment]
Thanks for the report. Luckily, this would only have caused issues on 16-bit systems where the size of tSaxmlContext is smaller than tParserContext - but it's still an error that needed to be fixed. I pushed an update.
